#!/usr/bin/env bash
# Build + install lampctl, plus a udev rule so it runs without sudo.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")" && pwd)"
PREFIX="${PREFIX:-/usr/local}"
BIN="$PREFIX/bin/lampctl"
RULES="/etc/udev/rules.d/99-lampctl.rules"

echo "==> Building lampctl (release)…"
cargo build --release --manifest-path "$REPO_DIR/Cargo.toml"

echo "==> Installing binary to $BIN (sudo)…"
sudo install -Dm0755 "$REPO_DIR/target/release/lampctl" "$BIN"

echo "==> Detecting HID LampArray devices…"
mapfile -t IDS < <("$BIN" list 2>/dev/null \
  | grep -oiE '[0-9a-f]{4}:[0-9a-f]{4}' | sort -u || true)

if [ "${#IDS[@]}" -eq 0 ]; then
  echo "    none detected right now — installing the example rule."
  sudo install -Dm0644 "$REPO_DIR/dist/99-lampctl.rules" "$RULES"
else
  echo "    found: ${IDS[*]}"
  {
    echo "# Generated by lampctl install.sh — HID LampArray device access."
    for id in "${IDS[@]}"; do
      up=$(echo "$id" | tr '[:lower:]' '[:upper:]')
      echo "KERNEL==\"hidraw*\", KERNELS==\"*${up}*\", MODE=\"0660\", GROUP=\"input\", TAG+=\"uaccess\""
    done
  } | sudo tee "$RULES" >/dev/null
fi

echo "==> Reloading udev…"
sudo udevadm control --reload-rules
sudo udevadm trigger --subsystem-match=hidraw --action=add || true

echo "==> Adding '$USER' to the 'input' group…"
sudo usermod -aG input "$USER" || true

cat <<EOF

Done. ✅
  • Binary:    $BIN
  • udev rule: $RULES

Log out and back in (so the 'input' group takes effect), then run:

  lampctl

EOF
